version: 2
jobs:
   build:
     working_directory: ~/code
     docker:
       - image: circleci/android:api-25-alpha
     environment:
           JVM_OPTS: -Xmx3200m

     dependencies:
       override:
          - chmod +x gradlew
     steps:
       - checkout
       - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
       - run:
            name: Download Dependencies
            command: ./gradlew androidDependencies